spring:
  profiles:
    active: native       

  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config   # points to config folder inside resources

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true