server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # allows dynamic routing using serviceId
          lower-case-service-id: true
      routes:
        - id: menu-service
          uri: lb://MENU-SERVICE
          predicates:
            - Path=/menu/**
          filters:
            - StripPrefix=1

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1

        - id: ui-service
          uri: lb://UI-SERVICE
          predicates:
            - Path=/**
          filters:
            - StripPrefix=0   # keep path as is (UI is serving JSPs directly)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

