spring:
  application:
    name: ui-service

admin-service:
  url: http://localhost:8087/api/admins

user-service:
  url: http://localhost:8088/api/branches

menu-service:
  url: http://localhost:8082
  
order-service:
  url: http://localhost:8083  