<<<<<<< HEAD
spring:
  application:
    name: user-service

  datasource:
    url: jdbc:h2:file:./data/userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  mvc:
    hiddenmethod:
      filter:
        enabled: true   # Support for PATCH and DELETE in forms
    view:
      prefix: /WEB-INF/views/  
      suffix: .jsp

server:
  port: 8088
=======
spring:
  application:
    name: user-service

  datasource:
    url: jdbc:h2:file:./data/userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  mvc:
    hiddenmethod:
      filter:
        enabled: true   # Support for PATCH and DELETE in forms
    view:
      prefix: /WEB-INF/views/  
      suffix: .jsp

server:
  port: 8088
>>>>>>> 201dda49cb3b15489c6d73ef904cb5fdb7fcbd72
